Repository remotemobprogramming/mob, pull requests merged in 2022-09, with the labels that each got.

#304 add function mob start --create
  CHANGELOG.md
  README.md
  mob.go
  mob_test.go
Labels: enhancement

#307 added tests for mob start create with parameter --branch
  mob_test.go
Labels: testing

#305 added reset warning and delete-remote-wip-branch parameter
  CHANGELOG.md
  mob.go
  mob_test.go
Labels: enhancement

#313 added tests and bump module version
  coauthors.go
  go.mod
  mob.go
  mob_test.go
  squash_wip.go
Labels: testing

#318 Remove style tag from README.md and move to _layouts/default.html
  README.md
  _layouts/default.html
Labels: hacktoberfest-accepted

#316 extracted help command
  configuration/configuration.go
  configuration/configuration_test.go
  help/help.go
  mob.go
  mob_test.go
  squash_wip.go
  squash_wip_test.go
  test/test.go
Labels: refactoring
