Repository remotemobprogramming/mob, pull requests merged in 2022-10, with the labels that each got.

#321 Better timer
  CHANGELOG.md
  mob.go
  mob_test.go
  test/test.go
Labels: enhancement

#325 simplified findMobTimerProcessIdsLinuxAndDarwin and fix mac CI build
  mob.go
  mob_test.go
Labels: refactoring

#335 Fix cli name detection on Windows
  mob.go
  mob_test.go
Labels: hacktoberfest-accepted
